### ISSUE TITLE
Update dependencies please

### ISSUE THREAD

**Issue by carrasc0** [appinioGmbH/flutter_packages#101]
In Podfile:
    appinio_social_share (from `.symlinks/plugins/appinio_social_share/ios`) was resolved to 0.0.1, which depends on
      FBSDKCoreKit (= 15.1.0)

**Comment by khanmujeeb687** [comment]
Hey @carrasc0 , FBSDK has been updated to version 16.0.1 in our plugin version 0.2.4.
