### ISSUE TITLE
Instagram Story sharing is overriding clipboard

### ISSUE THREAD

**Issue by RobertBrunhage** [appinioGmbH/flutter_packages#102]
Is it possible to share to instagram story without overriding the clipboard? 

Would like to be able to copy a text that is then possible to paste to to the story. I can see that the native iOS implementation is using the `UIPasteboard` so maybe this is not possible?

**Comment by khanmujeeb687** [comment]
Hey @RobertBrunhage , Right now I am not sure how we can implement this without using UIPasteboard. Or if it is even possible or not? Maybe you can also check this and create a PR or mention the link here.

**Comment by platonicsocrates** [comment]
+1 on this issue. @khanmujeeb687 can we reopen this?
