### ISSUE TITLE
[Feature] Video Player

### ISSUE THREAD

**Issue by tushar-bansal-22** [appinioGmbH/flutter_packages#105]
Can we add an optional option, to mute the video if the device is on silent/vibrate mode on developer's side

**Comment by khanmujeeb687** [comment]
Hey @tushar-bansal-22  , right now this feature is not available with this package but you can implement it at your end very easily. Just use [this](https://pub.dev/packages/volume_controller) package. And mute the video if device is on mute while to initialize.


`    _videoPlayerController = VideoPlayerController.network(
      longVideo,
    )
      ..initialize().then((value) async {
        _videoPlayerController.setVolume(await VolumeController().getVolume());
        setState(() {});
      });`
