### ISSUE TITLE
I cant increase the default cards to show (by default it is two)

### ISSUE THREAD

**Issue by kaushik-utkarsh** [appinioGmbH/flutter_packages#106]
![image](https://github.com/appinioGmbH/flutter_packages/assets/91653952/04f7ef59-b34c-405e-8612-257fbf78c3b4)
i want by default 3 cards no matter how many is the length of the total cards.

Can anyone please help me and tell me how to do it?

**Comment by khanmujeeb687** [comment]
Hey @kaushik-utkarsh , from the next version you will be able to provide a count of cards you want to show in the background.
