### ISSUE TITLE
Hide controlBar automatically after few seconds

### ISSUE THREAD

**Issue by sperochon** [appinioGmbH/flutter_packages#11]
Hello, thanks for your package!

Could you please add the feature to hide the controlBar automatically after few seconds? In my case, I start automatically the video playing (with videoPlayerController.play()) and so would like to hide this controlBar.

Thanks!

**Comment by tobiasbentin** [comment]
Yes it will be included with the update coming next week. There you ca set the `autoFadeOutControls` and  `durationAfterControlsFadeOut` parameters.

**Comment by sperochon** [comment]
@tobiasbentin Thanks for your work. Unfortunately, I have used another package since my original post. I hope your work will serve others. 👍
