### ISSUE TITLE
Add the possibility of customizing the background cards (size, opacity, scale)

### ISSUE THREAD

**Issue by pbouttier** [appinioGmbH/flutter_packages#118]
Hi

The plugin is great but I would have liked to be able to customize the cards. 

For example, have them closer together (`_backgroundCardsDifference`), change the opacity (add a new parameter `_backgroundCardsOpacityDifference`?), the scale (`_backgroundCardsScaleDifference`).

Similar to https://pub.dev/packages/card_swiper 

Thanks

**Comment by khanmujeeb687** [comment]
Hey @pbouttier , This feature will be hopefully available in the next version.
