### ISSUE TITLE
When I share pictures and texts in Ios Telegram, the picture does not go away

### ISSUE THREAD

**Issue by onguc** [appinioGmbH/flutter_packages#120]
Hello. my code is like below:

`
AppinioSocialShare appinioSocialShare = AppinioSocialShare();`     
`
appinioSocialShare.shareToTelegram(
"Telegram Test Message",
filePath: product.productUrl);`

But only "Telegram Test Message" is delivered. 

May you help?

**Comment by khanmujeeb687** [comment]
Hey @onguc , as we have mentioned in the comment in `appinio_social_share_platform_interface.dart`.

`  ///filepath only works for android
  Future<String> shareToTelegram(String message, {String? filePath}) {
    throw UnimplementedError('platformVersion() has not been implemented.');
  }`
  
  
  We are currently sharing only text messages in case of telegram.
