### ISSUE TITLE
Social share not working for android

### ISSUE THREAD

**Issue by jakobheb** [appinioGmbH/flutter_packages#121]
I'm currently facing the problem that instagram is not opening when I want to share to story. 
There is just a message "W/NetworkRequest(13291): No App Check token for request."
I followed the introduction on pub.dev, but still not working

Thank you very much

**Comment by khanmujeeb687** [comment]
Hey @jakobheb , it doesn't seem like a social_share plugin's bug, have you enabled app check for your app?

**Comment by jakobheb** [comment]
How can you enable that?

**Comment by jakobheb** [comment]
In iOS its working fine

**Comment by jakobheb** [comment]
This is my AndroidManifest
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="app.gainback.gainback_app_2">

    <queries>
        
        
        <package android:name="com.instagram.android" />
        <package android:name="com.instagram.share.ADD_TO_STORY" />
        <package android:name="com.facebook.katana" />
        <package android:name="com.facebook.orca" />
        <package android:name="org.telegram.messenger" />
        <package android:name="com.whatsapp" />
        <package android:name="com.twitter.android" />

        <provider android:authorities="com.facebook.katana.provider.PlatformProvider" /> 
        <provider android:authorities="com.facebook.orca.provider.PlatformProvider" /> 
    </queries>

    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.INTERNET" />

    
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />

    <application
        android:label="Gainback"
        android:name="${applicationName}"
        android:icon="@mipmap/launcher_icon"
        android:requestLegacyExternalStorage="true">

 
        <meta-data android:name="com.facebook.sdk.AutoLogAppEventsEnabled"
            android:value="true"/>

        <provider android:name="androidx.core.content.FileProvider"
            android:authorities="${applicationId}.provider"
            android:exported="false" android:grantUriPermissions="true">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/provider_paths_app" />
        </provider>


        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
                android:name="io.flutter.embedding.android.NormalTheme"
                android:resource="@style/NormalTheme"
                />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>

        </activity>

        <provider android:name="com.facebook.FacebookContentProvider" android:authorities="com.facebook.app.FacebookContentProvider4.....0"
            android:exported="true" />
        <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id" />
        <meta-data android:name="com.facebook.sdk.ClientToken" android:value="@string/facebook_client_token" />
        

        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>



</manifest>


`

Did I do anything wrong??

**Comment by jakobheb** [comment]
Hey @khanmujeeb687, shareToInstagramDirect is working and shareToWhatsApp also, just shareToInstagramStory and shareToInstagramFeed isn't.
Any idea why it's not working
