### ISSUE TITLE
ShareToInstagramStory is not working well Please help me

### ISSUE THREAD

**Issue by yongdo-kim** [appinioGmbH/flutter_packages#126]
If I press the button to call appinioSocialShare.shareToInstagramStory, I got SUCCESS as the result. However, the white screen appears and immediately turns off. Why is this happening? Should I add a separate setting on Facebook Developer? Most api calls are blocked.

I'd appreciate it if you could give me a reply.

**Comment by khanmujeeb687** [comment]
Hey @yongdo-kim , have you followed the readme correctly? On which device is this happening?
