### ISSUE TITLE
Auto play video

### ISSUE THREAD

**Issue by faizan1947** [appinioGmbH/flutter_packages#129]
I'm not finding any parameter to turn on auto-play video

**Comment by 4A6F6F6E61** [comment]
You can just call the `play` function on the normal `VideoPlayerController` after the player has been initialised:
```Dart
videoPlayerController = VideoPlayerController.networkUrl(Uri.tryParse(widget.url) ?? Uri())
      ..initialize().then((value) {
        setState(() {});
        videoPlayerController.play();
      });
```

**Comment by khanmujeeb687** [comment]
Hey @faizan1947 , closing this issue because the approach by @4A6F6F6E61 is correct and should work.
