### ISSUE TITLE
make filePath in shareToFacebook optional

### ISSUE THREAD

**Issue by stngcoding** [appinioGmbH/flutter_packages#134]
Currently the function required two params (hashtag, filePath), This is kinda weird because I can't share text only post

**Comment by khanmujeeb687** [comment]
Hey @stngcoding , we cannot share text. So we share hashtags. That's why the argument is named hashtag. And sharing only hashtags does not make sense so we share files also. 
If you have a fix to share only text, please create a PR and I will merge it.
