### ISSUE TITLE
[appinio_swiper] I want the animation of the sliding card to return to the back, what should I do?

### ISSUE THREAD

**Issue by lizhuoyuan** [appinioGmbH/flutter_packages#136]
like this:
https://gd-hbimg.huaban.com/6cf9189ba924e1853f88340fa94f91b07c11796179d17d-jBsHYv_fw1200

thank u

**Comment by khanmujeeb687** [comment]
Hey @lizhuoyuan , This link is not working. please check.

**Comment by khanmujeeb687** [comment]
Hey @lizhuoyuan , The link is not working, But in general if you want to unswipe, you can do it like this.

  final AppinioSwiperController controller = AppinioSwiperController();
  
  void unSwipe(){
    controller.unswipe();
  }
