### ISSUE TITLE
[appinio_social_share] [iOS] Background Color is not submitted to Instagram story share

### ISSUE THREAD

**Issue by Linaks** [appinioGmbH/flutter_packages#137]
I tried to share a picture with a background color to Instagram stories, but it doesn't work on iOS. On Android it works as intended.
Does anyone know what's the issue for that?

**Comment by khanmujeeb687** [comment]
Hey @Linaks , I just tested the latest version of appinio social share and The background color is actually working, Could you please share your code snipped?

`   await appinioSocialShare.shareToInstagramStory(
      facebookAppId,
      stickerImage: sticker,
      backgroundBottomColor: '#FAFAFA',
      backgroundTopColor: '#000000',
    );`

**Comment by Linaks** [comment]
You're right. I did some incorrect encoding of the RadixString by doing this:
`#${pictureColor.value.toRadixString(16)}`
However Android did the correct output.

Thank you for the hint @khanmujeeb687 :)
