### ISSUE TITLE
Hide picture-in-picture mode option

### ISSUE THREAD

**Issue by GAayushi** [appinioGmbH/flutter_packages#139]
Hello, I'm using   **appinio_video_player: ^1.2.1** And getting an option to display video in **PIP** mode. While I play video in PIP mode, I'm able to play multiple videos simultaneously, the previous video does not stop itself.
Also in PIP mode, I'm getting an option of **back to tab**, but that made the video playing in background. 
Is there a way to fix this, or Can we disable the PIP mode option??

**Comment by khanmujeeb687** [comment]
Hey @GAayushi , I am looking into this issue. Could you please share which OS is having this issue. Also if you can share a screen recording it will be very helpful to debug. Thanks!
