### ISSUE TITLE
Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null

### ISSUE THREAD

**Issue by rhowelp** [appinioGmbH/flutter_packages#14]
After I update to Flutter 3 and the latest version of Appinio 1.0.2. I am receiving this error

`/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/appinio_video_player-1.0.2/lib/src/controls/progress_bar_indicator.dart:95:22: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.`

**Comment by sagnik-sanyal** [comment]
Yeah I'm facing this issue after applying this package to my flutter app ( Currently on Flutter 3.0 stable channel ) . It would be really great if this issue gets fixed
