### ISSUE TITLE
Video not supported on android i'm getting this error.

### ISSUE THREAD

**Issue by Hardas-Dharani** [appinioGmbH/flutter_packages#141]
Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(2, null, null, video/avc, avc1.640032, -1, null, [1920, 1440, 30.000034], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES, null, null)

**Comment by nerufuyo** [comment]
Are you get an answer for this problem?

**Comment by khanmujeeb687** [comment]
I think this is the [same](https://stackoverflow.com/questions/69543538/cant-play-video-h-264-on-android-with-android-exoplayer-react-native-video) issue. Is it?
