### ISSUE TITLE
App fails to run on iOS simulator

### ISSUE THREAD

**Issue by kirillmesiats** [appinioGmbH/flutter_packages#147]
Launching lib/main.dart on iPhone 14 Pro in debug mode...
main.dart:1
Xcode build done.                                           37.7s
Exception: Unable to launch <package name> on 234EDC92-1C7C-40D3-A1C5-947058A4B898:
ProcessException: Process exited abnormally:
An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
The request to open <package name> failed.
The request was denied by service delegate (SBMainWorkspace).
Underlying error (domain=FBProcessExit, code=128):
	The operation couldn’t be completed. The process exited.
	The process exited.
  Command: xcrun simctl launch 234EDC92-1C7C-40D3-A1C5-947058A4B898 <package name> --enable-dart-profiling --start-paused --enable-checked-mode --verify-entry-points --enable-impeller=false
Error launching application on iPhone 14 Pro.
Exited

**Comment by bilalhamud** [comment]
@kirillmesiats What package are you using?

**Comment by khanmujeeb687** [comment]
Hey @kirillmesiats  , I am looking into it, The fix will be available in the next version.
