### ISSUE TITLE
FBSDKCoreKit upgrade

### ISSUE THREAD

**Issue by Tryad0** [appinioGmbH/flutter_packages#151]
Would appreciate an upgrade. Thanks a lot!

> [!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
  In Podfile:
    appinio_social_share (from `.symlinks/plugins/appinio_social_share/ios`) was resolved to 0.0.1, which depends on
      FBSDKCoreKit (= 16.0.1)

 >   flutter_facebook_auth (from `.symlinks/plugins/flutter_facebook_auth/ios`) was resolved to 6.0.1, which depends on
      FBSDKLoginKit (~> 16.1.3) was resolved to 16.1.3, which depends on
        FBSDKCoreKit (= 16.1.3)

**Comment by khanmujeeb687** [comment]
Hey @Tryad0 , @palsantosh , I am looking into it, The fix will be available in the next version.

**Comment by HarshuPatel007** [comment]
I am also facing the same error.

CocoaPods 1.12.1 is available.
To update use: `gem install cocoapods`

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.12.1

Analyzing dependencies
firebase_core: Using Firebase SDK version '10.12.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '10.12.0' defined in 'firebase_core'
Downloading dependencies
Installing AppsFlyerFramework (6.12.2)
Installing FBAEMKit (16.0.1)
Installing FBSDKCoreKit (16.0.1)
Installing FBSDKCoreKit_Basics (16.0.1)
Installing FBSDKShareKit (16.0.1)
Installing FMDB (2.7.5)
Installing Firebase (10.12.0)
Installing FirebaseCore (10.12.0)
Installing FirebaseCoreInternal (10.15.0)
Installing FirebaseInstallations (10.15.0)
Installing FirebaseMessaging (10.12.0)
Installing Flutter (1.0.0)
Installing GoogleDataTransport (9.2.5)
Installing GoogleUtilities (7.11.5)
Installing PromisesObjC (2.3.1)
Installing SAMKeychain (1.5.3)
Installing TikTokOpenSDK (5.0.14)

[!] Error installing TikTokOpenSDK
[!] /usr/bin/curl -f -L -o /var/folders/vm/301ky_p10fg04t7_6zv4g_gh0000gn/T/d20230921-45858-88qyje/file.zip https://sf16-muse-va.ibytedtos.com/obj/tiktok-open-platform/TikTokOpenSDK.xcframework-5.0.14.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.11.2 cocoapods-downloader/1.5.1'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0
curl: (28) Failed to connect to sf16-muse-va.ibytedtos.com port 443 after 75068 ms: Couldn't connect to server
Warning: Problem : timeout. Will retry in 1 seconds. 2 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0
curl: (28) Failed to connect to sf16-muse-va.ibytedtos.com port 443 after 75003 ms: Couldn't connect to server
Warning: Problem : timeout. Will retry in 2 seconds. 1 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0
curl: (28) Failed to connect to sf16-muse-va.ibytedtos.com port 443 after 75005 ms: Couldn't connect to server
