### ISSUE TITLE
[appinio_swiper] onSwiping should follow drop action

### ISSUE THREAD

**Issue by Nico04** [appinioGmbH/flutter_packages#155]
I'd like to use `onSwiping` & `onSwipeCancelled` callbacks to animate page background to indicate to user the relevant action it will be done when he will **drop** the card (lift his finger).
Currently, thoses callbacks doesn't reflect what action will be done when swipe gesture is over. 
For instance, if you start swiping on one side, but go back to the center to "cancel" the gesture, and lift your finger, it will cancel swipe action. But in that case, the `onSwiping` is only called when going to the other side, and `onSwipeCancelled` is only called when you drop the card. So there is currently no way to indicate to the user the action is going to do, in real time.

One idea would be to pass `null` to `onSwiping` when moving to a position where droping card would do nothing.

**Comment by bilalhamud** [comment]
Fixed with version 2.1.0
