### ISSUE TITLE
[Appinio Swiper] Need the current position of the card

### ISSUE THREAD

**Issue by nathan-poncet** [appinioGmbH/flutter_packages#166]
On my Appino Swiper, I would like to have the current card position in order to change other UI elements like background color or display some text.

**Comment by caseycrogers** [comment]
This times a thousand! I have icon buttons at the bottom for thumbs down/up (corresponding to swipe left/right). If the user is manually dragging a card, I want the corresponding button to expand and glow to give the user more feedback.

**Comment by caseycrogers** [comment]
The PR for this is done and ready to be reviewed:
#175

**Comment by bilalhamud** [comment]
Fixed with version 2.1.0
