### ISSUE TITLE
[appinio_video_player] add Cache support please....

### ISSUE THREAD

**Issue by gusk9999** [appinioGmbH/flutter_packages#168]
add cache support please :)

**Comment by narayanan-ka** [comment]
I bumped across his wonderful package but realized it doesn't have Caching which is a very important feature in video playback for flutter apps. There is another package cached_video_player which does caching separately but we cant use both in the same app. Perhaps this useful feature should be implemented ?

**Comment by khanmujeeb687** [comment]
Hey @narayanan-ka , Caching support will be available in the next version!

**Comment by narayanan-ka** [comment]
> Hey @narayanan-ka , Caching support will be available in the next version!

Thank you. Great
