### ISSUE TITLE
Detect Left or right swipe

### ISSUE THREAD

**Issue by romaankhanAndroid** [appinioGmbH/flutter_packages#17]
How to detect if card is left swiped or right swiped

**Comment by KubaStachecki** [comment]
Hi! Any update on this issue?

**Comment by eloipeloux** [comment]
Hello,

Wanted to know if someone figured how you can detect this, @bilalhammoud  maybe ? ;)

**Comment by bilalhammoud** [comment]
Solved with version 1.1.0

**Comment by eloipeloux** [comment]
Thanks a lot, it's being very useful !
I did something with listeners etc. but this is waaaaaay prettier with your add ons ;)

Cheers mate !
