### ISSUE TITLE
[Feature] : appinio_swiper background card angle

### ISSUE THREAD

**Issue by offline-first** [appinioGmbH/flutter_packages#187]
**Plugin name**
Appinio Swiper

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Can the background cards have an option to get a random angle? 

Example:
```dart
AppinioSwiper(
   backgroundCardOffset: const Offset(0, 30),
   backgroundCardScale: .95,
   backgroundCardRotationList: [-3, 2, -1], // <-- new property
)
....
```
```dart
 Transform.rotate(
   angle: widget.backgroundCardRotationList[index%widget.backgroundCardRotationList.length].degreeToAngle(), 
   child: ...
```

btw, nice lib 👍

**Comment by khanmujeeb687** [comment]
Hey @offline-first , It seems amazing, Since you already have a solution. You can just create a PR and I will try to merge it and release with the next version.

**Comment by offline-first** [comment]
Hello @khanmujeeb687 here is my PR #198
