### ISSUE TITLE
[ BUG ] : Appinio Swiper onSwipeEnd method behavior's

### ISSUE THREAD

**Issue by OsFoouad** [appinioGmbH/flutter_packages#191]
Plugin name : Appinio Swiper

onSwipeEnd: method , if i started to swipe card then release it without move it to any direction (mean the card release and still in  front )
the onSwipeEnd method called and this cause some unexpected things , like the values is updated . with the version 2.0.3 everything was fine. any misunderstand from me ?

**Comment by khanmujeeb687** [comment]
Hey @OsFoouad, The onSwipeEnd mehtod is getting called but with a different option please check the example app.

```
  void _swipeEnd(int previousIndex, int targetIndex, SwiperActivity activity) {
    switch (activity) {
      case Swipe():
        log('The card was swiped to the : ${activity.direction}');
        log('previous index: $previousIndex, target index: $targetIndex');
        break;
      case Unswipe():
        log('A ${activity.direction.name} swipe was undone.');
        log('previous index: $previousIndex, target index: $targetIndex');
        break;
      case CancelSwipe():
        log('A swipe was cancelled');
        break;
      case DrivenActivity():
        log('Driven Activity');
        break;
    }
  }
```
