### ISSUE TITLE
Zoom in and out of the screen

### ISSUE THREAD

**Issue by Ngochiendev** [appinioGmbH/flutter_packages#199]
When watching videos, I often zoom in on the screen and zoom out when no longer needed. What I mean here is when a user watches a video, can the user save the time spent watching?
The situation I encountered was that when I zoomed in and out, the video replayed from the beginning. Please give me the solution!

**Comment by khanmujeeb687** [comment]
Hey @Ngochiendev , I am looking into this issue. On which platform this is happening? Android?
