### ISSUE TITLE
[ BUG ] : FBSDKCoreKit and FBSDKShareKit outdate not permit Facebook advertising campaign

### ISSUE THREAD

**Issue by Paroca72** [appinioGmbH/flutter_packages#200]
Hello,

iOS issue.
With the current version of the packages when trying to start a Facebook advertising campaign I got an issue from Facebook that said need to update my Facebook SDK to the last release.

The solution I found was go inside the appinio_social_share.podspec and change this two line as follow, removing the versioning numbers:
  s.dependency 'FBSDKCoreKit'
  s.dependency 'FBSDKShareKit'

After "pod update" the SDK was updated at the latest version and the Facebook campaign now started proper.

Thanks for your support
Sam

**Comment by dioscuroi** [comment]
Thank you for the solution. It works like a charm!
