### ISSUE TITLE
CustomVideoPlayer is not compatible with Dismissible

### ISSUE THREAD

**Issue by Z6P0** [appinioGmbH/flutter_packages#205]
**Plugin name**

appinio_video_player

**Describe the bug**

CustomVideoPlayer is not compatible with Dismissible

**To Reproduce**

```dart
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Dismissible(
        key: UniqueKey(),
        direction: DismissDirection.vertical,
        child: Center(child: CustomVideoPlayer(customVideoPlayerController: customVideoPlayerController)),
        onDismissed: (direction) {
          Navigator.pop(context);
        },
      ),
    );
  }
```

**Expected behavior**

The player should be dismissed with swipe gesture.

**Comment by khanmujeeb687** [comment]
` Dismissible(
          key: UniqueKey(),
          direction: DismissDirection.horizontal,
          child: Center(
            child: CustomVideoPlayer(
              customVideoPlayerController: _customVideoPlayerController,
            ),
          ),
          onDismissed: (direction) {
            _customVideoPlayerController.dispose();
          },
        )
        `
        
        Hey @Z6P0 , Thanks for reporting the issue. you can dispose the controller on onDismissed and it should work.
