### ISSUE TITLE
[ BUG ] : Flutter instagram feed functionality is not working . Any solution?

### ISSUE THREAD

**Issue by sourabh-53** [appinioGmbH/flutter_packages#207]
**Plugin name**
For e.g. - Appinio social share

**Describe the bug**
I am using appinio_social_share library,I want to implement select the picture from gallery and post it on instagram feed. I have implemented the functions for Instagram post functionality. However, It takes me to feed page but saying that Can't continue editing,  Sorry, there was a problem editing your photo. A report has been sent to instagram. Everytime this error occur. If I select any picture either from camera or gallery. Why this happened. Any suggestions?

P.S I have integrated upgraded method of instagram and facebook methods.

**To Reproduce**
1. Select picture from gallery
2. Called following methods:
    var status =  await AppinioSocialSharePlatform.instance
                              .shareToInstagramFeed((await getCardPaths()));

getCardMethods returns list. 

3. It takes me to the instagram feed page with an error.

**Expected behavior**
It should open feed page with selected picture from previous screen.

**Screenshots**
Attached
![Screenshot_2023-12-09-00-11-27-51_1c337646f29875672b5a61192b9010f9](https://github.com/appinioGmbH/flutter_packages/assets/153464858/d874580d-f0d7-4616-822e-63ea59d59608)

**Smartphone (please complete the following information):**
 - Device: One Plus
 - OS: Android 12

**Comment by Paroca72** [comment]
After installed the latest version of the plugin (0.3.0) it started to happen also to me.

**Comment by gustavobrian** [comment]
hi, any solutions? please

**Comment by gustavobrian** [comment]
please, not work!!! thanks
