### ISSUE TITLE
[Feature] : Share image/video to Facebook Messenger

### ISSUE THREAD

**Issue by orkun1675** [appinioGmbH/flutter_packages#219]
**Plugin name**
Appinio social share

**Is your feature request related to a problem? Please describe.**
Users are not able to share images and videos to Messenger.

**Describe the solution you'd like**
It would be great if, like other methods, shareToMessenger() would allow passing an image/video.

**Describe alternatives you've considered**
The only alternative I can think of is instructing the users to download the image to their phone (Photos) and share it to Messenger from there

**Comment by khanmujeeb687** [comment]
Hello @orkun1675 , Currently I am not sure I we can achieve that natively. If you find any solutions , feel free to create a PR.
Thanks!

**Comment by khanmujeeb687** [comment]
Hey @orkun1675 , closing this ticket because no solution exist right now, If you find a solution in future, you can reopen this issue. Thanks!
