### ISSUE TITLE
[ BUG ] : The swiper reset the cardBuilder index when poping a route.

### ISSUE THREAD

**Issue by nathan-poncet** [appinioGmbH/flutter_packages#220]
**Plugin name**
Appinio Swiper

**Describe the bug**
When a card is pressed on the swiper, it pushes out a new route (GoRouter).
But if I pop this route and fall back in front of my swiper screen, the cardBuilder index is reset to 0, even if I've slid in several cards before. 

**To Reproduce**
1. Create a Swiper
2. Swipe many cards
3. Push a route when click on a card
4. Pop this route

**Expected behavior**
You should see the same card that was before you push the screen.

**Actual behavior**
The card you see if the first one of the stack

**Screenshots**
https://github.com/appinioGmbH/flutter_packages/assets/112613712/b6d4816c-d298-402c-b2a0-13df970e1fd9

**Comment by khanmujeeb687** [comment]
Hey @nathan-poncet , I tried to reproduce it but its working fine for me. Could you please share your code snippet?
