### ISSUE TITLE
[ BUG ] : shareToSMS no working

### ISSUE THREAD

**Issue by QuentinSc** [appinioGmbH/flutter_packages#224]
Hello again, and thank you for your work

**Appinio social share**

**Describe the bug**
I followed all the instruction in the READ.me.
Can't get it to work. 
Whatsapp and Telegram working great

**To Reproduce**
 ```
String response = await appinioSocialShare
            .shareToSMS('Test message');
```

**Expected behavior**
Open Messenger

**Actual behavior**
Nothing happens.
response is ""Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference""

**Smartphone (please complete the following information):**
 - Device: [Android Emulators, Galaxy S23]
 - OS: Android 13

**Comment by 2001arman** [comment]
Hello @khanmujeeb687. This error still appear on android version 13
