### ISSUE TITLE
CustomAspectRatio Portrait & Landscape view

### ISSUE THREAD

**Issue by RzTutul** [appinioGmbH/flutter_packages#23]
I set custom aspect ratio it worked portrait view but not working landscape view here I set Ratio: 0,54
![image](https://user-images.githubusercontent.com/37795928/184288207-c09783c2-4d11-49f9-884f-c06c190c0e51.png)

**Portrait View:** 
![image](https://user-images.githubusercontent.com/37795928/184287963-f3532f76-2c7b-401d-8f63-9f94e2092f94.png)
**landscape View:** 
![image](https://user-images.githubusercontent.com/37795928/184288025-497cc971-3830-4e1e-bac0-2a3ed2b70390.png)

**Comment by bilalhammoud** [comment]
Hey @RzTutul, can you share your code please?

**Comment by khanmujeeb687** [comment]
Hey @RzTutul , I tried to reproduce it but it's working fine. Could you please share your code?
