### ISSUE TITLE
[ BUG ] : shareToFacebook does not work

### ISSUE THREAD

**Issue by Winterteq** [appinioGmbH/flutter_packages#231]
**Plugin name**
Using AppInioSocialShare. the .shareToFacebook() function appears to throw a println error.

**Describe the bug**
The following is printed to console: `D/error   (19638): println needs a message`

**To Reproduce**
1. Call the following function: `appinioSocialShare.shareToFacebook(
                                        "message", [
                                      "/data/user/0/<app_name>/app_flutter/image.jpg"
                                    ]);`

**Expected behavior**
I would expect to see Facebook app appear with the image in an edit post screen. This works for Instagram and Whatsapp on the same device and image path.

**Smartphone (please complete the following information):**
 - Device: Samsung A20
 - OS: Android

**Comment by JasperElton** [comment]
Same issue here with Samsung A34 where shareToFacebook, shareToInstagramDirect, and shareToTelegram wont work and it causes a white frame to flick on the top status bar. Other that that all sharing to other apps are fine.

**Comment by dgurudot** [comment]
> Same issue here with Samsung A34 where shareToFacebook, shareToInstagramDirect, and shareToTelegram wont work and it causes a white frame to flick on the top status bar. Other that that all sharing to other apps are fine.

I am also facing the same issue and wondering how to solve this issue.
