### ISSUE TITLE
[ BUG ] : Wrong asset picking

### ISSUE THREAD

**Issue by Badar25** [appinioGmbH/flutter_packages#245]
**Plugin name**
 - Appinio social share 

**Describe the bug**
While downloading and writing it in temp directory using path_provider, and passing the same path but still it picks random video from my gallery and forwarding it for sharing for tiktok, instagram. Is this a bug? Its happening on iOS only.

**Expected behavior**
It should pick exact video which im passing

**Screenshots**
This is my code, downloading asset from storage and passing it to appinio.
<img width="852" alt="image" src="https://github.com/appinioGmbH/flutter_packages/assets/122017969/285af3a8-501c-4241-9d14-2a7194656314">

**Smartphone (please complete the following information):**
 - Device: iphone 12 PRO
 - OS: ios 16.4  
 - package version: latest 

**Addition**
I have confirmed the video which im downloading is different and appinio is sharing different video, while deleting that random video, it still picked another random video from my gallery.

**Comment by Badar25** [comment]
I think there was something wrong with video formate, i have changed the video and its now working fine

**Comment by Badar25** [comment]
its still happening

**Comment by khanmujeeb687** [comment]
Hey @Badar25 , According the code we wrote for sharing to tiktok. We save the asset to user gallery and then pick it from there, is your asset getting saved? Can you see it in photos?

**Comment by Badar25** [comment]
Yes but then you guys are sorting it via date and thats why its picking
wrong asset

**Comment by khanmujeeb687** [comment]
Yes @Badar25 , you mean sorting is the problem? are you able to find a workaround?

**Comment by Badar25** [comment]
Yes, before saving just saving the date as now instead of using original
date of the video/content

**Comment by Badar25** [comment]
I will create PR soon

**Comment by lucakramberger** [comment]
i am also not able to share to tiktok post. the image is saved to my gallery and tiktok opens but after a loading dialog in tiktok i just get redirected to my redirect url

**Comment by khanmujeeb687** [comment]
Hey @lucakramberger , have you added `TikTokClientKey` to your info.plist?
