### ISSUE TITLE
[BUG] Version 0.3.0 not allowing to upload the image or video files on the twitter from iOS

### ISSUE THREAD

**Issue by PoriyaBytez** [appinioGmbH/flutter_packages#246]
Appinio social share 0.3.0

After updating this version, I am no longer to share any multimedia file on Twitter from iOS. I have iOS 17.3 OS. What I suspected is that version 0.2.6 also stops working in iOS while sharing the files on Twitter. I have tried my old test flight build where the image and video upload were working fine, unfortunately, that test flight version also not working. Is anyone having the issue? Is anyone who resolved the issue?

To Reproduce
1. Select any files from the gallery
2. Click on share on Twitter, you need to have the Twitter app installed on your device
3. It will only show the spinner for some time and then it will go away, you can't track any error or issue there

I need help here if someone already resolved the issue or if someone can guide me on it.

**Comment by lisovyk** [comment]
I can't share to twitter event on android – `AppinioSocialSharePlatform.instance.getInstalledApps()` returns false for twitter, though latest version is installed. Could it be connected to renaming of twitter to X ?
