### ISSUE TITLE
[Feature] : Explain usage of MANAGE_EXTERNAL_STORAGE in the readme

### ISSUE THREAD

**Issue by lisovyk** [appinioGmbH/flutter_packages#250]
**Package**:
Appinio social share

**Is your feature request related to a problem? Please describe.**
Would be good to know beforehand that `MANAGE_EXTERNAL_STORAGE` permission requires additional approval from Google, and is not needed to use app cache storage. So, if developers do not need to access outside files, like my case, there is no need to include it. 

**Describe the solution you'd like**
Add a disclaimer to the readme, explaining what the permissions are for, and stress that MANAGE_EXTERNAL_STORAGE should not be used without a good reason.

**Additional context**
With MANAGE_EXTERNAL_STORAGE, you will get `Your scoped storage permission declaration needs to be updated.` when uploading to google play.

Good resource:
https://developer.android.com/training/data-storage/manage-all-files#all-files-access-google-play

**Comment by lisovyk** [comment]
I don't want to create anothe thread, but I suspect similar thing goes for 
```
 <key>NSPhotoLibraryUsageDescription</key>
  <string>$(PRODUCT_NAME) needs permission to access photos and videos on your device</string>
  <key>NSMicrophoneUsageDescription</key>
  <string>$(PRODUCT_NAME) does not require access to the microphone.</string>
  <key>NSCameraUsageDescription</key>
  <string>$(PRODUCT_NAME) requires access to the camera.</string>
  <key>NSAppleMusicUsageDescription</key>
  <string>$(PRODUCT_NAME) requires access to play music</string>
```
in `Info.plist`

**Comment by lisovyk** [comment]
Is day or is self expansionary - you can do everything that is not connected to the user's files. So:
Create a picture in your apps folder and send it to SM - yes
Choose a picture from users photos - nope, need said permissions

**Comment by Purvik-Bigshorts** [comment]
For selecting pictures, I believe`READ_MEDIA_IMAGE` is more than enough. I would like to know specific for `MANAGE_EXTERNAL_STORAGE` permission as it requires declaration on play store if we're having it in manifest.
