### ISSUE TITLE
Unable to share to instagram post

### ISSUE THREAD

**Issue by ehtiqamar** [appinioGmbH/flutter_packages#271]
**Plugin name**
Appinio Social Share

**Describe the bug**
Unable to share to instagram stories

logs:

W/System.err( 4311): android.content.ActivityNotFoundException: Unable to find explicit activity class {com.instagram.android/com.instagram.share.handleractivity.ShareHandlerActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?
W/System.err( 4311): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2376)
W/System.err( 4311): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:2009)
W/System.err( 4311): 	at android.app.ContextImpl.startActivity(ContextImpl.java:1132)
W/System.err( 4311): 	at android.app.ContextImpl.startActivity(ContextImpl.java:1103)
W/System.err( 4311): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:436)
W/System.err( 4311): 	at com.appinio.socialshare.appinio_social_share.utils.SocialShareUtil.shareFileAndTextToPackage(SocialShareUtil.java:385)
W/System.err( 4311): 	at com.appinio.socialshare.appinio_social_share.utils.SocialShareUtil.shareToInstagramFeed(SocialShareUtil.java:80)
W/System.err( 4311): 	at com.appinio.socialshare.appinio_social_share.AppinioSocialSharePlugin.decideApp(AppinioSocialSharePlugin.java:97)
W/System.err( 4311): 	at com.appinio.socialshare.appinio_social_share.AppinioSocialSharePlugin.onMethodCall(AppinioSocialSharePlugin.java:66)
W/System.err( 4311): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
W/System.err( 4311): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
W/System.err( 4311): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
W/System.err( 4311): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
W/System.err( 4311): 	at android.os.Handler.handleCallback(Handler.java:958)
W/System.err( 4311): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err( 4311): 	at android.os.Looper.loopOnce(Looper.java:232)
W/System.err( 4311): 	at android.os.Looper.loop(Looper.java:334)
W/System.err( 4311): 	at android.app.ActivityThread.main(ActivityThread.java:8291)
W/System.err( 4311): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 4311): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:557)
W/System.err( 4311): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)

**To Reproduce**
1. Implement appinio social share
2. Share to Instagram post

**Smartphone (please complete the following information):**
 - Device: Nothing Phone 2
 - OS: Android 14
 - Version 0.3.1

**Comment by khanmujeeb687** [comment]
Hey @ehtiqamar, This issue happens when the targetted app is not installed. Please check again!
