### ISSUE TITLE
[ BUG ] :  Failed to find configured root that contains /data/data/com.music.impapp/cache/tempImage.jpg , image share is not working

### ISSUE THREAD

**Issue by mohamed-815** [appinioGmbH/flutter_packages#273]
**Plugin name**
For e.g. - Appinio social share , Appinio Swiper etc.

**Describe the bug**

**To Reproduce**
1. Step 1
2. Step 2
3. Step 3
4. Step 4

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mohamed-815** [comment]
image share is not working, it showing some path issue to twitter D/error   (24672): Failed to find configured root that contains /data/data/com.music.impapp/cache/tempImage.jpg

**Comment by trexcodes** [comment]
share any video or image

**Comment by mohamed-815** [comment]
ok

**Comment by bharatmk256** [comment]
To solve the issue instead of using documented path:

``<?xml version="1.0" encoding="utf-8"?>
<paths>
    <external-path
        name="external_files"
        path="." />
</paths>``

Try using this path:

`<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <cache-path
        name="cache_files"
        path="/"/>
</paths>`

**Comment by ayyuby26** [comment]
> To solve the issue instead of using documented path:
> 
> `<?xml version="1.0" encoding="utf-8"?> <paths> <external-path name="external_files" path="." /> </paths>`
> 
> Try using this path:
> 
> `<?xml version="1.0" encoding="utf-8"?> <paths xmlns:android="http://schemas.android.com/apk/res/android"> <cache-path name="cache_files" path="/"/> </paths>`

It worked before, but now it's an error
`
E/DatabaseUtils(17101): Writing exception to parcel
E/DatabaseUtils(17101): java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://com.eraproperty.provider/cache_files/64898.jpg from pid=13761, uid=10168 requires the provider be exported, or grantUriPermission()
E/DatabaseUtils(17101): 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:820)
E/DatabaseUtils(17101): 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:684)
E/DatabaseUtils(17101): 	at android.content.ContentProvider$Transport.enforceFilePermission(ContentProvider.java:674)
E/DatabaseUtils(17101): 	at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:548)
E/DatabaseUtils(17101): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:327)
E/DatabaseUtils(17101): 	at android.os.Binder.execTransactInternal(Binder.java:1154)
E/DatabaseUtils(17101): 	at android.os.Binder.execTransact(Binder.java:1123)
`

**Comment by ayyuby26** [comment]
> To solve the issue instead of using documented path:
> 
> `<?xml version="1.0" encoding="utf-8"?> <paths> <external-path name="external_files" path="." /> </paths>`
> 
> Try using this path:
> 
> `<?xml version="1.0" encoding="utf-8"?> <paths xmlns:android="http://schemas.android.com/apk/res/android"> <cache-path name="cache_files" path="/"/> </paths>`

It worked before, but now it's an error
`
E/DatabaseUtils(17101): Writing exception to parcel
E/DatabaseUtils(17101): java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://com.xxx.provider/cache_files/64898.jpg from pid=13761, uid=10168 requires the provider be exported, or grantUriPermission()
E/DatabaseUtils(17101): 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:820)
E/DatabaseUtils(17101): 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:684)
E/DatabaseUtils(17101): 	at android.content.ContentProvider$Transport.enforceFilePermission(ContentProvider.java:674)
E/DatabaseUtils(17101): 	at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:548)
E/DatabaseUtils(17101): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:327)
E/DatabaseUtils(17101): 	at android.os.Binder.execTransactInternal(Binder.java:1154)
E/DatabaseUtils(17101): 	at android.os.Binder.execTransact(Binder.java:1123)
`

**Comment by khanmujeeb687** [comment]
hey @ayyuby26 , Did you follow the documentation correctly?
Please check again and try the latest version https://pub.dev/packages/appinio_social_share

**Comment by DavidOrakpo** [comment]
I have ran into this exact bug again. I've done the correct set up in my manifest and strings.xml as the document said
