### ISSUE TITLE
[Feature] : Compatibility with FBSDKCoreKit 17.0.0

### ISSUE THREAD

**Issue by farukoflaz** [appinioGmbH/flutter_packages#275]
Hi guys,

**Plugin name**
Appinio social share

**Is your feature request related to a problem? Please describe.**
For privacy concerns of Apple we need to update FBSDKCoreKit to 17.0..0 but this package is not compatible with it.

**Describe the solution you'd like**
New update is needed.

Thank you

**Comment by shanelic** [comment]
Are there any news about the updates?

**Comment by suzyvivi** [comment]
In my `pubspec.yaml`
```
appinio_social_share: ^0.3.1
flutter_facebook_auth: ^6.0.4
```

ERROR：
[!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
  In Podfile:
    appinio_social_share (from `.symlinks/plugins/appinio_social_share/ios`) was resolved to 0.0.1, which depends on
      FBSDKCoreKit (= 16.1.3)

    flutter_facebook_auth (from `.symlinks/plugins/flutter_facebook_auth/ios`) was resolved to 6.2.0, which depends on
      FBSDKLoginKit (~> 17.0.0) was resolved to 17.0.0, which depends on
        FBSDKCoreKit (= 17.0.0)



How should I resolve the error message that appears when I run `pod install` for my project?
