### ISSUE TITLE
[ BUG ] : sharetofacebook not working

### ISSUE THREAD

**Issue by lim-freddy** [appinioGmbH/flutter_packages#283]
**Appinio social share**

**Describe the bug**
I already follow all instruction on readme. When i trigger sharetofacebook in android emulator, nothing happen and the script not continue, even not entering catch and finally block.

In android studio log, there is this message:
Apps that target Android API 30+ (Android 11+) cannot call Facebook native apps unless the package visibility needs are declared. Please follow https://developers.facebook.com/docs/android/troubleshooting/#faq_267321845055988 to make the declaration.

i use library appinio_social_share 3.0.1, flutter version 3.3.8, target sdk version 33, build gradle 7.0.0

**Comment by khanmujeeb687** [comment]
Hey @lim-freddy , you need to mention this inside your app's androidmanifest file, We have already mentioned it here in the [documentation](https://pub.dev/packages/appinio_social_share).  
Closing this issue, If you still need any help, please reopen this issue.
Thanks! 


![Screenshot 2024-07-21 at 23 22 51](https://github.com/user-attachments/assets/e65b3917-5b4f-4d3c-986b-1b3cd5baa12c)
