### ISSUE TITLE
No attributionURL when sharing to instagram story

### ISSUE THREAD

**Issue by lucakramberger** [appinioGmbH/flutter_packages#286]
await AppinioSocialShare().iOS.shareToInstagramStory(
              KeyStore.FACEBOOKAPPID,
              backgroundImage: backgroundPath,
              stickerImage: stickerPath,
              attributionURL: url,
            );

when calling the instagram story share function, the background and sticker image is working fine, but the attributionURL is not added in the story

**Comment by Hwangjunhong** [comment]
@lucakramberger 
I too have the same problem.
Did you solve it?

**Comment by lucakramberger** [comment]
> @lucakramberger I too have the same problem. Did you solve it?

Nope, unfortunately I think the instagram api does not support a url anymore

**Comment by khanmujeeb687** [comment]
Hey @lucakramberger , [Seems like ](https://stackoverflow.com/questions/65627605/sharing-instagram-stories-with-open-app-link)the attributionUrl only works for some accounts with extra features maybe based on followers.

**Comment by khanmujeeb687** [comment]
closing this issue since it can't be handled by our side. If you still need some help with this @lucakramberger, reopen this thread.
