### ISSUE TITLE
[Feature] : Sharing image to WhatsApp iOS

### ISSUE THREAD

**Issue by migueloli** [appinioGmbH/flutter_packages#287]
**Plugin name**
Appinio social share

**Is your feature request related to a problem? Please describe.**
We can't share image and text or even only image to WhatsApp, before we also couldn't using the native share, but now native share is allowing to share to WhatsApp with image and text.

**Describe the solution you'd like**
Adding the possibility to share image and/or text to WhatsApp. Not only be limited to sharing text.

**Comment by migueloli** [comment]
Hello,

Any chances of this being worked any time in the future?

Thank you

**Comment by khanmujeeb687** [comment]
Hey @migueloli, This feature is in testing and will be available in the next version.

**Comment by migueloli** [comment]
Thank you very much @khanmujeeb687

**Comment by khanmujeeb687** [comment]
Hey @migueloli , do you have any native implementation for iOS?

**Comment by khanmujeeb687** [comment]
Hey @migueloli It is possible to share images to whatsapp using appinio_social_share: ^0.3.1 version. If you find an iOS implementation, feel free to create a PR. Thanks!
