### ISSUE TITLE
[ BUG ] : Twitter share character limit issue: Unable to post tweet.

### ISSUE THREAD

**Issue by ucpritam** [appinioGmbH/flutter_packages#288]
**Plugin name**
Appinio social share.

**Describe the bug**
I cannot post a tweet even if my Twitter character limit is under 280 characters. I am using the appinioSocialShare.iOS.shareToTwitter() method.

**To Reproduce**
1. Use appinio_social_share: ^0.3.1
2. Pass some text to appinioSocialShare.iOS.shareToTwitter().
3. Post icon is disabled and twitter character limit is showing in negative.

**Expected behavior**
I should be able to post tweet as my character limit is under 280 characters.

**Screenshots**
![Screenshot 2024-05-23 at 15 11 02](https://github.com/appinioGmbH/flutter_packages/assets/54333597/c5043b60-1b20-41e0-96f8-676e86b34c66)
![Screenshot 2024-05-23 at 15 23 17](https://github.com/appinioGmbH/flutter_packages/assets/54333597/73b70966-34aa-4b56-961d-652d277d1856)

**Smartphone:**
 - Device: iPhone 13
 - OS: iOS
 - Version 17.4.1

**Here is my code**
`await appinioSocialShare.iOS.shareToTwitter(message, file.path);`

**Comment by ucpritam** [comment]
Any fix? @khanmujeeb687

**Comment by ucpritam** [comment]
@khanmujeeb687, I have tried using plain text, but the issue persists. 
I have identified the bug in you code which exists in ShareUtil.swift (Line no. 479), where you are adding the text twice. 
Although this works on older iOS versions, this problem occurs on the latest iOS version (> iOS 16).

**Comment by khanmujeeb687** [comment]
Hey @ucpritam , I have added a condition for that line now based on ios version, and it still works for ios 18 beta. I hope this will fix your issue. This change will be available in next version of our plugin. Thanks :)

**Comment by ucpritam** [comment]
Great Thanks!
