### ISSUE TITLE
[appinio_swipper] NoSuchMethodError

### ISSUE THREAD

**Issue by SEGVeenstra** [appinioGmbH/flutter_packages#30]
When you don't provide the `onSwipe` callback a default callback is used (`emptyFunctionIndex`).
However, this function is missing the `direction` property which crashes the app with a `NoSuchMethodError`:

```console
Closure call with mismatched arguments: function 'emptyFunctionIndex'
Receiver: Closure: (int, AppinioSwiperDirection) => void from Function 'emptyFunctionIndex': static.
Tried calling: emptyFunctionIndex(3, Instance of 'AppinioSwiperDirection')
```

### Solution

Update the signature of `emptyFunctionIndex`

**Comment by SEGVeenstra** [comment]
I've opened a PR with the fix:
https://github.com/appinioGmbH/flutter_packages/pull/29

**Comment by bilalhammoud** [comment]
Thanks @SEGVeenstra, already live with version 1.1.1

**Comment by SEGVeenstra** [comment]
Great @bilalhammoud !
I have a few more suggestions to improve the package, are you open for those? Should I open an new issue for them?
