### ISSUE TITLE
Tiktok share for iOS

### ISSUE THREAD

**Issue by quseappdeveloper** [appinioGmbH/flutter_packages#32]
Any idea on when tiktok will be added for iOS

**Comment by bilalhammoud** [comment]
Hi @quseappdeveloper,  it is on our list for next week

**Comment by quseappdeveloper** [comment]
Great. Also for Facebook and Instagram share videos sharing works correct?

**Comment by quseappdeveloper** [comment]
Any update on when this will be available for iOS?

Thanks,
Nitesh

**Comment by quseappdeveloper** [comment]
Any luck with the TikTok support for iOS?

**Comment by quseappdeveloper** [comment]
Any update on supporting TikTok share in iOS?

**Comment by loic-hamdi** [comment]
+1

**Comment by loic-hamdi** [comment]
@bilalhamud  
Documentation [https://github.com/appinioGmbH/flutter_packages/tree/main/packages/appinio_social_share#usage](https://github.com/appinioGmbH/flutter_packages/tree/main/packages/appinio_social_share#usage) needs update for iOS `shareToTiktokStatus ` & `shareToTiktokPost `
