### ISSUE TITLE
shareToInstagramStory() method on IOS

### ISSUE THREAD

**Issue by Cglassm** [appinioGmbH/flutter_packages#325]
Using `shareToInstagramStory` method i got this result `ERROR_APP_NOT_AVAILABLE` in IOS. Anybody can help?

**Comment by opensourcekam** [comment]
@Cglassm how did you fix / debug this?

**Comment by yelkamel** [comment]
I have the same

**Comment by vinayOB** [comment]
Do any one know how to fix this?
