### ISSUE TITLE
shareToFacebook not opening Facebook App on Android

### ISSUE THREAD

**Issue by matthew-codev** [appinioGmbH/flutter_packages#33]
Hi @bilalhammoud , I just want to thank you and the team for the great effort you had done on this package.

I tried the package on our app and it is working great on Facebook Story, Instagram Story, Twitter, but i can't seem to make the shareFacebook work on Android.

I am just receiving this on the logs.

```
I/Timeline(23537): Timeline: Activity_launch_request time:406551299
```

It is weird because I can launch the Facebook app using Facebook Story. I hope you can help me on this. Thanks!

**Comment by matthew-codev** [comment]
Ok I got it, it seems like I have set the `android:exported` to false. It is actually working now.

```
 <provider android:authorities="@string/fb_provider_id"
             android:name="com.facebook.FacebookContentProvider"
             android:exported="true"/>

**Comment by bilalhammoud** [comment]
Perfect, then I will close this issue.
