### ISSUE TITLE
customVideoPlayerProgressBarSettings isn't work

### ISSUE THREAD

**Issue by RebeccaWang0221** [appinioGmbH/flutter_packages#4]
I downloaded version 1.0.1, but when I was trying to add customVideoPlayerProgressBarSettings, it showed `The named parameter 'customVideoPlayerProgressBarSettings' isn't defined. Try correcting the name to an existing named parameter's name, or defining a named parameter with the name `

Other than this, wonderful package!

**Comment by bilalhammoud** [comment]
Hi @RebeccaWang0221, can you please provide a full example of your code?
