### ISSUE TITLE
Option for isFullscreenByDefault

### ISSUE THREAD

**Issue by Alii-isk** [appinioGmbH/flutter_packages#45]
Hello, could someone add the ability to auto fullscreen by default as and option for `CustomVideoPlayerSettings `

**Comment by tobiasbentin** [comment]
Hello @Alii-isk,
this package already contains this feature.
In the ```CustomVideoPlayerSettings``` you can set the ```enterFullscreenOnStart``` to ```true```. This will bring your video to fullscreen whenever you play the video.
