### ISSUE TITLE
[appinio_social_share] [shareToInstagramFeed] Error with sharing on Instagram Feed

### ISSUE THREAD

**Issue by sadatd** [appinioGmbH/flutter_packages#51]
# Sharing on Instagram feed error
Error occurs on both IOS and Android.
Tested on:
- iOS 16.2 20C65
- Android 9 
## Flutter doctor output
```
[✓] Flutter (Channel beta, 3.6.0-0.1.pre, on macOS 13.1 22C65 darwin-arm64, locale en-XK)
    • Flutter version 3.6.0-0.1.pre on channel bet
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 75927305ff (7 weeks ago), 2022-11-17 05:52:50 +0530
    • Engine revision b754eabc98
    • Dart version 2.19.0 (build 2.19.0-374.1.beta)
    • DevTools version 2.19.0
```
## Debug console output
```
[core] "Error returned from daemon: Error Domain=com.apple.accounts Code=7 "(null)""
[PAAccessLogger] Failed to log access with error: access=<PATCCAccess 0x2827c0be0> accessor:<<PAApplication 0x28276f110 identifierType:auditToken identifier:{pid:35176, version:104392}>> identifier:AC2CC600-E2A4-4674-9729-C677482DF158 kind:intervalEvent timestampAdjustment:0 visibilityState:0 assetIdentifierCount:0 tccService:kTCCServicePhotos, error=Error Domain=NSCocoaErrorDomain Code=4097 "connection to service named com.apple.privacyaccountingd" UserInfo={NSDebugDescription=connection to service named com.apple.privacyaccountingd}
```

## Error's screenshot from Instragram
<img src="https://user-images.githubusercontent.com/15090688/210579868-35376af4-6712-40bf-91bf-891274192a9e.png" width=300/>

**Comment by khanmujeeb687** [comment]
Hi @sadatd , This happens when your Instagram app does not have access to all the photos. So you can try to give Photos/Gallery permission to Instagram and try again.

**Comment by sadatd** [comment]
> Hi @sadatd , This happens when your Instagram app does not have access to all the photos. So you can try to give Photos/Gallery permission to Instagram and try again.

Hi @khanmujeeb687, If permission to all photos is given to Instagram then it works. I also tried with  'Selected photos' permission, it doesn't give error but it passes photo from those selected ones, not photo from the app. Is there some workaround for this.

**Comment by khanmujeeb687** [comment]
Hey @sadatd I am not sure if it is possible, because we save the video to photos app and share the localIdentifier for the asset to Instagram, and Instagram picks the asset using that localIdentifier. So If the permission for that asset is not provided. that will not work.
