### ISSUE TITLE
[Appinio Swiper] SingleChildScrollView position doesn't reset when swiping cards.

### ISSUE THREAD

**Issue by heltonoliveirasuzuki** [appinioGmbH/flutter_packages#54]
Hi, 

I'm currently using Appinio swiper with SingleChildScrollView in every card. So if I scroll to the end of a card the scroll position stays unchanged as I swipe to the next.  Is there a way to reset the scroll position reset every time I swipe? 

PS: Every object that is displayed in each card has its own key but Appinio doesn't seem to recognize it automatically.

<img width="570" alt="Screenshot 2023-01-10 at 10 34 12 PM" src="https://user-images.githubusercontent.com/106628957/211711896-727128d8-5341-4ea2-ac1a-2789f3f09df9.png">

I'd greatly appreciate if anyone knows how to fix this. 
Thank you in advance!

**Comment by khanmujeeb687** [comment]
Hey @altanarata , Could you please add a key to the root component of your card item and try again? I tried the same and it worked for me.

<img width="731" alt="Screenshot 2023-03-09 at 08 46 57" src="https://user-images.githubusercontent.com/58891556/223955499-044eaa47-d3c0-4834-8cc8-ebd1219c478e.png">
