### ISSUE TITLE
[appinio_social_share] all share file  error

### ISSUE THREAD

**Issue by tudosxxx** [appinioGmbH/flutter_packages#55]
final image = await ImagePicker().pickImage(source: ImageSource.gallery);
    print(image!.path);
    appinioSocialShare.shareToSMS('aaa',filePath: image.path);
    appinioSocialShare.shareToTwitter('aaa',filePath: image.path);
    appinioSocialShare.shareToInstagramFeed(image.path);

I/flutter (18277): /data/user/0/com.giftools.itse/cache/image_picker7266606595833541220.jpg
D/error   (18277): Failed to find configured root that contains /data/data/com.giftools.itse/cache/image_picker7266606595833541220.jpg
I/chatty  (18277): uid=10711(com.giftools.itse) identical 1 line
D/error   (18277): Failed to find configured root that contains /data/data/com.giftools.itse/cache/image_picker7266606595833541220.jpg

**Comment by tudosxxx** [comment]
/data/user/0/com.giftools.itse/cache/image_picker7266606595833541220.jpg
/data/data/com.giftools.itse/cache/image_picker7266606595833541220.jpg

**Comment by khanmujeeb687** [comment]
Hey @tudosxxx 
I think you are missing the below configuration in AndroidManifest.xml file. Please check [this](https://pub.dev/packages/appinio_social_share) page to configure your app before using this plugin. 

![Screenshot 2023-01-23 at 13 38 52](https://user-images.githubusercontent.com/58891556/214041720-3593031d-1341-4896-a0c1-9cd086b4a81e.png)
