### ISSUE TITLE
[appinio_social_share] shareToFacebook doesn't share text on iOS. It shows image only on Facebook post sharing.

### ISSUE THREAD

**Issue by cjuanliew** [appinioGmbH/flutter_packages#56]
It is able to share text and image to Facebook on Android. Similar issue on shareToWhatsapp, it share text only without image on iOS.

**Comment by cjuanliew** [comment]
Any chances to share with text/url on Fb as both are showing on Android ? :(

**Comment by cjuanliew** [comment]
> hey, @cjuanliew shareToFacebook only supports sharing hashtags for Ios, So sharing a text without space in between will work (but as a hashtag). Also, shareToWhatsApp only shares text because Whatsapp currently doesn't provide sharing both simultaneously for Ios.

Hashtag doesn't work on iOS even the text is without space

**Comment by khanmujeeb687** [comment]
Hey @cjuanliew . I am checking this issue, could you please share the error logs if there are any?

**Comment by khanmujeeb687** [comment]
Hey @cjuanliew , which version of the plugin are you using? I just rechecked the feature and its working fine for me.

![IMG_659C3899BFE1-1](https://user-images.githubusercontent.com/58891556/227833865-0928d985-6e27-4b49-8d49-5b71ba1a619b.jpeg)
