### ISSUE TITLE
[Swiper] Infinite loop

### ISSUE THREAD

**Issue by morey6757** [appinioGmbH/flutter_packages#59]
Hello !

thank you for your beautiful Swiper :-)

This widget can it infinite loop ?
(when all card swiped, i want to unswiped automaticaly all cards)

Thank you :-)

**Comment by ricardodalarme** [comment]
nope, but I created a fork that can do this: https://pub.dev/packages/flutter_card_swiper

**Comment by morey6757** [comment]
> nope, but I created a fork that can do this: https://pub.dev/packages/flutter_card_swiper

Thanks @ricardodalarme !!! It's works perfectly :-) Great !!!
