### ISSUE TITLE
[appinio_video_player] Orientation on iOS does not work

### ISSUE THREAD

**Issue by saulrmzlpz** [appinioGmbH/flutter_packages#62]
Orientation on iOS does not work when playing a video and needs to be viewed in landscape mode.

Debug console output:
`[Orientation] BUG IN CLIENT OF UIKIT: Setting UIDevice.orientation is not supported. Please use UIWindowScene.requestGeometryUpdate(_:)`

Package version:  `appinio_video_player: ^1.2.0`
Device: iPhone 13 Pro Max iOS 16.3

**Comment by CharbelHaddadSoftImpact** [comment]
did you fix it ?

**Comment by saulrmzlpz** [comment]
> did you fixed it ?

No. This issue still in the package. I am thinking of doing a fork of this repository to fix it.
