### ISSUE TITLE
[appinio_social_share] shareToFacebook crashes on Android 12 device (Samsung Galaxy s10)

### ISSUE THREAD

**Issue by btbishop93** [appinioGmbH/flutter_packages#64]
On Android 12 device, the generic function `AppinioSocialShare()
        .shareToFacebook(');` starts, but then crashes, the window it should go to appears for a split second, crashes, and then there is no return made to the caller. Here is my code...

*Note: the AppinioSocialShare().shareToFacebookStory function works just fine.

```
Future<bool> _shareFacebook(
      String imgPath, BuildContext context, SocialShareType platform) async {
    var shareData = await AppinioSocialShare()
        .shareToFacebook('#DriveFoodForward', imgPath);

    // Does not even get to this point, it crashes on AppinioSocialShare().shareToFacebook() method.
    if (shareData == 'SUCCESS') {
      _updateRecentSocialShare(
        recentSocialShareInsert: DateTime.now(),
        platform: platform,
      );
    } else {
      print(shareData);
    }
    return true;
  }
```

I included video where you can see it flash like it is trying to launch the modal for sharing to facebook and then it just craps out. Also, on iOS this is working fine.

https://user-images.githubusercontent.com/5323528/216793488-34764a23-6c2a-4509-b155-99785a1a3923.mp4

**Comment by Codeclopedia** [comment]
hey @khanmujeeb687 any update on this issue? Because i'm facing the same thing in android devices. It is working fine on ios device but crashing while opening in android devices

**Comment by sadatd** [comment]
> Hey @btbishop93 , please try adding these to queries in the android manifest.
> 
> ```
>       <provider android:authorities="com.facebook.katana.provider.PlatformProvider" /> 
>         <provider android:authorities="com.facebook.orca.provider.PlatformProvider" /> 
> ```

Hey @khanmujeeb687, still same with added providers. It works with older Android version (tested with 9).

**Comment by btbishop93** [comment]
I will try on my end as well and report back.
