### ISSUE TITLE
Video Not Playing in Firefox Browser?

### ISSUE THREAD

**Issue by DazzlingCVa** [appinioGmbH/flutter_packages#65]
I was upload mp4 and mkv and mov format videos and i am checking in firefox browser. the video was not playing. It Shows No Video is Supported Format and MIME Found.
So anybody can fix it. pls, it was urgent.
pls Reply me.

**Comment by khanmujeeb687** [comment]
Hello @DazzlingCVa, I just tested .mp4, .mkv and .mov formats and apart from .mkv other two formats are working fine. I did some research and found out that firefox does not support .mkv file format at the moment.
