### ISSUE TITLE
Flutter 3.7.3 Video Player Not Working?

### ISSUE THREAD

**Issue by supremedraculaking** [appinioGmbH/flutter_packages#66]
I Uploaded the Video In the Carousel Slider. It Will Show only a black screen.
If I Put Selection Area for Scaffold Video Gets Black Screen.
But if I double-tap the video it will play on full-screen mode. but not playing in normal mode. so quickly fix them pls.
No overlay widget error has occurred.
Can anybody pls fix them quickly?
Or Give a Solution pls.

**Comment by tasaddaq-hussain** [comment]
Yes its not working please give any solution!

**Comment by bilalhamud** [comment]
Just tested it with flutter 3.7.7 and it is working on iOS, android & Web

@tasaddaq-hussain @supremedraculaking would you like to provide an example code?
