### ISSUE TITLE
appinio_swiper 1.1.1 - detect slide

### ISSUE THREAD

**Issue by Junesui** [appinioGmbH/flutter_packages#69]
How to detect whether the sliding is completed, or cancel the left and right sliding

**Comment by khanmujeeb687** [comment]
Hey @Junesui , You can use **onSwipe**  callback to know when the swipe is completed.
 `AppinioSwiper(
              unlimitedUnswipe: true,
              controller: controller,
              unswipe: _unswipe,
              cards: cards,
              onSwipe: _swipe,
              padding: const EdgeInsets.only(
                left: 25,
                right: 25,
                top: 50,
                bottom: 40,
              ),
            ),`

**Comment by khanmujeeb687** [comment]
> or cancel the left and right sliding
Do you mean how can we restrict the horizontal sliding??
