### ISSUE TITLE
Customise Finish Button Theme 

### ISSUE THREAD

**Issue by Vadime** [appinioGmbH/flutter_packages#71]
## Problem
I wold like to use this flutter package in my app.
But I use a custom Theme on all of my widgets, so this package seems kinda of in my app, because it does not follow the apps theme.
The primary color is read perfectly fine. But there are things I would like to be able to customise as well.
For example:
1. Border radius
2. Elevation

## Solution
Maybe you could make the finish button read from the app's global theme, where all the custom attributes are declared. 
Or you could directly put those custom attributes into the constructor

Thank you in advance

**Comment by khanmujeeb687** [comment]
Hey @Vadime, I am looking into this issue, which plugin are you using?

**Comment by Vadime** [comment]
I'm using the flutter_onboarding_slider.

**Comment by bilalhamud** [comment]
Solved with version 1.0.9
