### ISSUE TITLE
[Question] Package clone

### ISSUE THREAD

**Issue by DominicOrga** [appinioGmbH/flutter_packages#72]
Hi there, I just wanted to know the connection of this package with the [flutter_card_swiper](https://pub.dev/packages/flutter_card_swiper) package.
They look identical in terms of code and documentation. 
Will this package soon be deprecated? Or is the latter an illegitimate one?

**Comment by khanmujeeb687** [comment]
Hey @DominicOrga, It is an illegitimate package.
