### ISSUE TITLE
Social share: Images/Sticker etc. are not shown in instagram story

### ISSUE THREAD

**Issue by jakobheb** [appinioGmbH/flutter_packages#74]
The images are not shown and a grey screen appears in the story section.

Any ideas how to solve that

`Future<void> shareToInstagram(String message, String filePath) async {
    await appinioSocialShare.shareToInstagramStory(backgroundImage: "assets/restaurants/habaneros.jpg", backgroundBottomColor: "", backgroundTopColor: "", backgroundVideo: "", stickerImage: "");
  }`

**Comment by khanmujeeb687** [comment]
Hey @jakobheb , you have to pass the image path from your device's storage not the asset path.

you can use image picker or any other plugin to pick media from the device or capture a pic and share.

**Comment by jakobheb** [comment]
Thank you very much

**Comment by jakobheb** [comment]
`String? image;

  Future pickImage() async {
    try {
      final image = await ImagePicker().pickImage(source: ImageSource.gallery);

      if(image == null) return;

      final imageBytes = await image.readAsBytes();
      final base64Image = base64Encode(imageBytes);

      setState(() => this.image = base64Image);
    } on PlatformException catch(e) {
      print('Failed to pick image: $e');
    }
  }

  Future pickImageC() async {
    try {
      final image = await ImagePicker().pickImage(source: ImageSource.camera);

      if(image == null) return;

      final imageBytes = await image.readAsBytes();
      final base64Image = base64Encode(imageBytes);

      setState(() => this.image = base64Image);
    } on PlatformException catch(e) {
      print('Failed to pick image: $e');
    }
  }

  AppinioSocialShare appinioSocialShare = AppinioSocialShare();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: CustomAppBar(title: 'Post'),
      body: Column(
        children: [
          ElevatedButton(
              onPressed: (){
              pickImage();

          },
              child: const Text("Galerie")),
          ElevatedButton(
            child: const Text("ShareToInstagram"),
            onPressed: () {

              shareToInstagram("message", image!);
            },
          ),
        ],
      ),
    );
  }
  Future<void> shareToInstagram(String message, String filePath) async {
    await appinioSocialShare.shareToInstagramStory(backgroundImage: filePath, backgroundBottomColor: "", backgroundTopColor: "", backgroundVideo: "", stickerImage: "");
  }`

still grey screen. Any ideas?

**Comment by jakobheb** [comment]
Even if I add the absolute path of an image, it is showing black screen

**Comment by khanmujeeb687** [comment]
Hey @jakobheb , I tried to reproduce it but it worked fine for me.

Could you please try using the below code and make sure the issue is in social share plugin.

`
  Future<void> pickImage() async {
    XFile? xFile = await ImagePicker.platform.getImage(
      source: ImageSource.gallery,
    );
    if (xFile != null) {
      String path = xFile.path;
      shareToInstagram(path);
    }
  }

  Future<void> shareToInstagram(String filePath) async {
    await appinioSocialShare.shareToInstagramStory(
      backgroundImage: filePath,
      stickerImage: filePath,
    );
  }
  `

**Comment by jakobheb** [comment]
Hey @khanmujeeb687, it is working pretty fine now, thank you. 

But I have another problem, I have the sticker in Firestore, how can I add the sticker from there. Its a string/website.

Is this possible??
