### ISSUE TITLE
Apps that target Android API 30+ (Android 11+) cannot call Facebook native apps 

### ISSUE THREAD

**Issue by tudosxxx** [appinioGmbH/flutter_packages#78]
Apps that target Android API 30+ (Android 11+) cannot call Facebook native apps unless the package visibility needs are declared. Please follow https://developers.facebook.com/docs/android/troubleshooting/#faq_267321845055988 to make the declaration.
![image](https://user-images.githubusercontent.com/52568890/225574104-e0e6524f-a46f-44d1-9ec0-bc2f3d00661c.png)

**Comment by khanmujeeb687** [comment]
Hey @tudosxxx , This issue was fixed in version 0.2.3.
