### ISSUE TITLE
Swiper: Can you add a LIKE / NOPE while dragging

### ISSUE THREAD

**Issue by bettysteger** [appinioGmbH/flutter_packages#81]
I would like to have a more tinder feel, for example when you are currently dragging a card (without releasing) to the right a big green LIKE appears on the top left corner of the swipe card. See this [screenshot](https://www.virtuallocation.com/images/tinder/tinder-swipe-3.jpg). 

Is this possible? `onSwipe` callback is too late :(

**Comment by bettysteger** [comment]
Same question: https://stackoverflow.com/q/75844336/595152

**Comment by mohitclover** [comment]
Same Question

**Comment by khanmujeeb687** [comment]
Hey @bettysteger , @mohitclover This feature will be available in next release.

**Comment by richardvt** [comment]
No...but I need to remove the badge (LIKE & NOPE) when dragging back to original position. There's no event to fire.

**Comment by vanosidor** [comment]
Please add swipe progress property to track card dragging to initial position. Thanks!
