### ISSUE TITLE
Network video url initialize takes time

### ISSUE THREAD

**Issue by RzTutul** [appinioGmbH/flutter_packages#83]
I am trying to build video reels like Instagram or TikTok. I used appinio_video_player 1.2.0 but when I swap a new video then it takes time to initialize. I initialized the controller at initState. can you resolve this?

**Comment by khanmujeeb687** [comment]
Hey, @RzTutul are you using PageView?

**Comment by RzTutul** [comment]
@khanmujeeb687  Yes i used PageView

**Comment by RzTutul** [comment]
@khanmujeeb687  I tried PreLoadPageView but It is playing all the videos at the same time. Also, it is not disposing of the video controller of the previous page while scrolling to the next page. Could you please help me out with this?

  @override
  Widget build(BuildContext context) {
    return new PreloadPageView.builder(
      itemCount: ...,
      itemBuilder: ...,
      onPageChanged: (int position) {...},
      .....
      preloadPagesCount: 3,
      controller: PreloadPageController(),
    );
  }

**Comment by khanmujeeb687** [comment]
Hey @RzTutul , Since you have set the preloadPagesCount to 3 so it will keep the current , previous and next page loaded. If you want only the current video to play then maybe you can set the videos to pause by default or maybe you can find some other workaround for that.

**Comment by khanmujeeb687** [comment]
If you are familiar with [provider](https://pub.dev/packages/provider) and already using it in your project for state management. Then you can store the currentVideoId in a variable and add a listener to it, so when it changes so depending upon the ID you can play and pause the video.
