### ISSUE TITLE
CustomVideoPlayerPopupSettings is not exported from public [appinio_video_player]

### ISSUE THREAD

**Issue by AlexSmirnov9107** [appinioGmbH/flutter_packages#89]
I need to import  CustomVideoPlayerPopupSettings from 
```
import 'package:appinio_video_player/src/models/custom_video_player_popup_settings.dart';
```
<img width="798" alt="image" src="https://user-images.githubusercontent.com/32673518/231179683-fbbcbe08-1eb3-474b-bbea-2132e10082ab.png">
so it cause the warnings.

**Comment by khanmujeeb687** [comment]
Hey @AlexSmirnov9107 , you just need to import `import 'package:appinio_video_player/appinio_video_player.dart';
` and it should work.
