### ISSUE TITLE
Is It possible that show third card when we have more than two cards? [appinio_swiper]

### ISSUE THREAD

**Issue by hasimyerlikaya** [appinioGmbH/flutter_packages#92]
Hi,

Thank you for that fantastic package.

I want to show a third card if cards count more than two.
Is it possible to determine the visible card count?

Thank you.

**Comment by richardvt** [comment]
I need this parameter. I just want one card to be visible.
Thanks.

**Comment by khanmujeeb687** [comment]
Hey @hasimyerlikaya , This feature will be available in the next version.

**Comment by hasimyerlikaya** [comment]
@khanmujeeb687  Thank you. Is it possible that you add the initialIndex option too? I added it myself. I think it will be useful for other users too.

<img width="752" alt="image" src="https://github.com/appinioGmbH/flutter_packages/assets/7986394/06f564d7-3e0d-4f45-972f-9d6b0216303b">
