### ISSUE TITLE
The repo is 85 MB and 53 MB is one single GIF 😨😨😨😨😨😨😨😨😨

### ISSUE THREAD

**Issue by mariopepe** [appinioGmbH/flutter_packages#93]
😨😨😨😨😨😨😨😨😨😨😨😨😨😨😨😨😨😨

wanted to make a PR, but got dissuaded by this fact

**Comment by khanmujeeb687** [comment]
Hey @mariopepe which plugin ??

**Comment by mariopepe** [comment]
the [flutter_packages](https://github.com/appinioGmbH/flutter_packages) repo.

The file is called: [zoom gif](https://github.com/appinioGmbH/flutter_packages/blob/main/assets/widget_zoom/zoom.gif)
